name: Main - apply policies to environments in https://app.kosli.com

on:
  push:
    branches:
      - main

env:
  KOSLI_ORG:       ${{ vars.KOSLI_ORG }}               # cyber-dojo
  KOSLI_HOST:      ${{ vars.KOSLI_HOST }}              # https://app.kosli.com
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_DRY_RUN:   ${{ vars.KOSLI_DRY_RUN }}           # false
  KOSLI_DEBUG:     ${{ vars.KOSLI_DEBUG }}             # false
  KOSLI_AWS_BETA:  aws-beta
  KOSLI_AWS_PROD:  aws-prod

jobs:

  apply-policies-to-environments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create/Update Kosli Policies
        run: |
          kosli create policy artifact-provenance      policies/artifact-provenance.yml
          kosli create policy build-process            policies/compliant-build-process.yml
          kosli create policy pull-request             policies/pull-request.yml
          kosli create policy post-build-security-scan policies/post-build-security-scan.yml

      - name: Attach policies to environments
        run: |
          kosli attach-policy artifact-provenance      --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          kosli attach-policy build-process            --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          kosli attach-policy pull-request             --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          kosli attach-policy post-build-security-scan --environment="${KOSLI_AWS_PROD}"

      - name: Detach policies from environments
        run: |
          kosli detach-policy security-scan        --environment="${KOSLI_AWS_PROD}"
