name: Main - apply policies to environments in https://app.kosli.com

on:
  push:
    branches:
      - main

env:
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  KOSLI_DRY_RUN:   ${{ vars.KOSLI_DRY_RUN }}           # true/false
  KOSLI_DEBUG:     ${{ vars.KOSLI_DEBUG }}             # true/false
  KOSLI_HOST:      ${{ vars.KOSLI_HOST }}              # https://app.kosli.com
  KOSLI_ORG:       ${{ vars.KOSLI_ORG }}               # cyber-dojo
  KOSLI_AWS_BETA:  aws-beta
  KOSLI_AWS_PROD:  aws-prod

jobs:

  apply-policies-to-environments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

#      - name: Tag Kosli Flows
#        run: |
#          kosli tag flow creator-ci                --set kind=microservice
#          kosli tag flow custom-start-points-ci    --set kind=microservice
#          kosli tag flow dashboard-ci              --set kind=microservice
#          kosli tag flow differ-ci                 --set kind=microservice
#          kosli tag flow exercises-start-points-ci --set kind=microservice
#          kosli tag flow languages-start-points-ci --set kind=microservice
#          kosli tag flow nginx-ci                  --set kind=microservice
#          kosli tag flow runner-ci                 --set kind=microservice
#          kosli tag flow saver-ci                  --set kind=microservice
#          kosli tag flow web-ci                    --set kind=microservice

      - name: Create/Update Kosli Policies
        run: |
          # kosli create policy default-policy default-env-policy.yml
          # kosli create policy snyk-policy    snyk-env-policy.yml
          #
          kosli create policy artifact-provenance policies/artifact-provenance.yml
          kosli create policy trail-compliance    policies/trail-compliance.yml
          kosli create policy security-scan       policies/security-scan.yml
          kosli create policy pull-request        policies/pull-request.yml

      - name: Attach policies to environments
        run: |
          #kosli detach-policy default-policy --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          #kosli detach-policy snyk-policy    --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          #
          kosli attach-policy artifact-provenance --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          #kosli attach-policy trail-compliance    --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          #kosli attach-policy security-scan       --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
          #kosli attach-policy pull-request        --environment="${KOSLI_AWS_PROD},${KOSLI_AWS_BETA}"
