name: Main - apply policies to environments in https://app.kosli.com

on:
  push:
    branches:
      - main

env:
  KOSLI_DRY_RUN: ${{ vars.KOSLI_DRY_RUN }}           # False
  KOSLI_HOST: ${{ vars.KOSLI_HOST }}                 # https://app.kosli.com
  KOSLI_ORG: ${{ vars.KOSLI_ORG }}                   # cyber-dojo
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}


jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: ${{ vars.KOSLI_CLI_VERSION }}

      - name: Create/Update Kosli Policies
        run: |
          kosli create policy default-policy default-env-policy.yml
          kosli create policy temp-policy temp-env-policy.yml
          kosli create policy snyk-policy snyk-env-policy.yml

      - name: Attach policies to environments
        run: |
          kosli attach-policy default-policy --environment=aws-prod,aws-beta
          kosli detach-policy temp-policy --environment=aws-prod,aws-beta
          kosli attach-policy snyk-policy --environment=aws-prod,aws-beta
